from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[3]
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
FEATURES_DATA_DIR = DATA_DIR / "features"


# ---- DWD weather data ----

DWD_DATA_DIR_RAW = RAW_DATA_DIR / "dwd"
DWD_DATA_DIR_PROCESSED = PROCESSED_DATA_DIR / "dwd"
DWD_DATA_DIR_FEATURES = FEATURES_DATA_DIR / "dwd"

# Solar
DWD_SOLAR_DATA_DIR_RAW = DWD_DATA_DIR_RAW / "solar"
DWD_SOLAR_DATA_DIR_PROCESSED = DWD_DATA_DIR_PROCESSED / "solar"
DWD_SOLAR_DATA_DIR_FEATURES = DWD_DATA_DIR_FEATURES / "solar"

# Wind
DWD_WIND_DATA_DIR_RAW = DWD_DATA_DIR_RAW / "wind"
DWD_WIND_DATA_DIR_FEATURES = DWD_DATA_DIR_FEATURES / "wind"


# ---- MaStR plant data ----

MASTR_DATA_DIR_RAW = RAW_DATA_DIR / "mastr"
MASTR_GESAMTDATENUEBERSICHT_PATH = MASTR_DATA_DIR_RAW / "Gesamtdatenexport_20260101_25.2.zip"

# Solar
MASTR_SOLAR_PLANTS_CSV_PATH = MASTR_DATA_DIR_RAW / "solar/einheiten_solar_20260101_25.2.csv"
MASTR_SOLAR_PLANTS_SQLITE_PATH = MASTR_DATA_DIR_RAW / "solar/einheiten_solar_20260101_25.2.db"

MASTR_WIND_PLANTS_CSV_PATH = MASTR_DATA_DIR_RAW / "wind/einheiten_wind_20260101_25.2.csv"
MASTR_WIND_PLANTS_SQLITE_PATH = MASTR_DATA_DIR_RAW / "wind/einheiten_wind_20260101_25.2.db"


# ---- SMARD generation data ----

SMARD_RAW_DATA_DIR = RAW_DATA_DIR / "smard"

# Solar
SMARD_SOLAR_DATA_DIR_RAW = SMARD_RAW_DATA_DIR / "solar"
SMARD_SOLAR_GENERATION_SERIES_JSON_TEMPLATE = SMARD_SOLAR_DATA_DIR_RAW / "solar_series_{start}_{end}.json"
